### ISSUE TITLE
postman compilation error

### ISSUE THREAD

**Issue by Busch-Matthew** [reminder-bot/postman-rs#1]
**Error when running "cargo build --release"**
> error returned from database: 1054 (42S22): Unknown column 'image_url' in 'field list'
> error returned from database: 1146 (42S02): Table 'reminders.embed_fields' doesn't exist
> error returned from database: 1054 (42S22): Unknown column 'image_url' in 'field list'

**Adding image_url to the SQL Database under embeds resolved the first error, but more missing fields appeared:**
> error returned from database: 1054 (42S22): Unknown column 'thumbnail_url' in 'field list'
> error returned from database: 1054 (42S22): Unknown column 'footer' in 'field list'

**Comment by JellyWX** [comment]
You just need to use the file from here to setup the database first: https://github.com/reminder-bot/reminder-rs/blob/master/create.sql
